name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        board: [pico, pico_w]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: |
          sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
      - name: configure + build
        run: |
          cmake . -B build -DPICO_BOARD=${{ matrix.board }}
          make -C build -j$(nproc)

